name = "backend-hono"
main = "src/index.ts"
compatibility_date = "2026-03-14"
compatibility_flags = ["nodejs_compat"]

workers_dev = false
routes = [{ pattern = "nodal.roitium.com", custom_domain = true }]

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "nodal-resources"
